In [ ]:
class student:
     _id_counter=1

     def __init__(self,name):
          self.stude_id=student._id_counter
          student._id_counter+=1
          self.name=name
          self.grades={}
          self.enrolled_cour = []

     def __str__(self):
          return f"studen id:{self.stude_id},name: {self.name}"
     
     def __repr__(self):
          return f"studen id:{self.stude_id},name: {self.name}"
     
     def add_grade()


In [3]:
s1=student("llllll")
s1

In [ ]:
class course:
     _id_counter=1
     def __init__(self,name):
          self.course_id=course._id_counter
          course._id_counter+=1
          self.name=name
          self.enroled_students=[]


     def __repr__(self):
          return f"{self.course_id},...{self.name},.......{self.}"

In [ ]:
class Student:
    _id_counter = 1
   
    def __init__(self, name):
        self.student_id = Student._id_counter
        Student._id_counter += 1
        self.name = name
        self.grades = {}
        self.enrolled_courses = []
    def __str__(self):
        return f"Student ID: {self.student_id},Name: {self.name} , Grades: {(self.grades)}"
       
    def __repr__(self):
        return f"Student ID: {self.student_id},Name: {self.name} , Grades: {(self.grades)}"
         
    def add_grade(self, course_id, grade):
        self.grades[course_id] = grade
   
    def enroll_in_course(self, course):
        self.enrolled_courses.append(course)

In [ ]:
class Course:
    _id_counter = 1
    def __init__(self, name):
        self.course_id = Course._id_counter
        Course._id_counter += 1
        self.name = name
        self.enrolled_students = []
    def __repr__(self):
        return f"course ID: {self.course_id}, Name = {self.name}, Enrolled :{len(self.enrolled_students)}"
   
    def enroll_student(self, student):
        if student not in self.enrolled_students:
            self.enrolled_students.append(student)
            print("student enrolled successfully!.")
        else:
            print("student already enrolled!.")
    def remove_student(self, student):
        if student in self.enrolled_students:
            

In [ ]:
  def __init__(self):
        self.students = {}
        self.courses = {}
   
    def add_student(self, name:str):
        """"
       
        """
        student = Student(name)
        self.students[student.student_id] = student
        print("Student added successfully!.")
        return student.student_id
   
    def remove_student(self, student_id):
        if student_id in self.students:
            student = self.students[student_id]
            if not student.enrolled_courses:
                del self.students[student_id]
                print("Student removed successfully.")
            else:
                print("Student has enrolled courses . cannot remove")
        else:
            print("Invalid std ID")
           
    def add_course(self, name):
        course = Course(name)
        self.courses[course.course_id] = course
        print("Course added successfully!")
        return course.course_id
   
    def remove_course(self, course_id):

In [1]:
l=[1,2,3]
import numpy as np
v1=np.array([2,4,6])
v2=np.array([5,5,10])
print(v1.dot(v2))



90


In [3]:
m1=np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
print(m1)
print("==============")
m2=np.array([[1,5,9],
             [7,5,3],
             [8,6,4]])
print(m2)
print("==============")
print(m1.dot(m2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 5 9]
 [7 5 3]
 [8 6 4]]
[[ 39  33  27]
 [ 87  81  75]
 [135 129 123]]
